# fly.toml app configuration file generated for moj-dzemat-donje-mostre on 2026-04-22T19:10:27+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'moj-dzemat-donje-mostre'
primary_region = 'fra'
kill_signal = 'SIGTERM'
kill_timeout = '30s'

[experimental]
  auto_rollback = true

[build]
  dockerfile = 'Dockerfile'

[env]
  DATABASE_URL = 'file:/litefs/data.db'
  NODE_ENV = 'production'
  PORT = '3000'
  PRIMARY_REGION = 'fra'
  TZ = 'Europe/Sarajevo'

[[mounts]]
  source = 'litefs'
  destination = '/var/lib/litefs'
  initial_size = '3gb'

[[services]]
  protocol = 'tcp'
  internal_port = 3000
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'requests'
    hard_limit = 120
    soft_limit = 80

  [[services.http_checks]]
    interval = '15s'
    timeout = '5s'
    grace_period = '30s'
    method = 'get'
    path = '/resources/healthcheck'
    protocol = 'http'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
