import { DAY_MS, DAY_SECONDS, MINUTE_SECONDS } from "#app/lib/time";

export const MIN_PASSWORD_LENGTH = 10;
export const MIN_PASSWORD_LENGTH_MESSAGE = `Lozinka mora imati najmanje ${MIN_PASSWORD_LENGTH} znakova.`;

const PASSWORD_RESET_TOKEN_TTL_MINUTES = 10;
export const PASSWORD_RESET_TOKEN_TTL_LABEL = `${PASSWORD_RESET_TOKEN_TTL_MINUTES} minuta`;
export const PASSWORD_RESET_TOKEN_TTL_SECONDS = PASSWORD_RESET_TOKEN_TTL_MINUTES * MINUTE_SECONDS;

const SESSION_MAX_AGE_DAYS = 30;
export const SESSION_MAX_AGE_MS = SESSION_MAX_AGE_DAYS * DAY_MS;
export const SESSION_MAX_AGE_SECONDS = SESSION_MAX_AGE_DAYS * DAY_SECONDS;
