import { MINUTE_SECONDS } from "#app/lib/time";

export const MIN_PASSWORD_LENGTH = 10;
export const MIN_PASSWORD_LENGTH_MESSAGE = `Lozinka mora imati najmanje ${MIN_PASSWORD_LENGTH} znakova.`;

const PASSWORD_RESET_TOKEN_TTL_MINUTES = 10;
export const PASSWORD_RESET_TOKEN_TTL_LABEL = `${PASSWORD_RESET_TOKEN_TTL_MINUTES} minuta`;
export const PASSWORD_RESET_TOKEN_TTL_SECONDS = PASSWORD_RESET_TOKEN_TTL_MINUTES * MINUTE_SECONDS;
